name: Go

on:
  push:
    branches: [ "main", "renovate/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # ensure we don't run multiple times on PRs from renovate branches
    if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate/')
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Unit Test
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Coverage
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
